apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: blackjack-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "<<REPLACE WITH YOUR BOOKINFO APP URL>>"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackjack
spec:
  hosts:
  - "<<REPLACE WITH YOUR BOOKINFO APP URL>>"
  gateways:
  - blackjack-gateway
  http:
  - match:
    - uri:
        exact: /blackjack.html
    - uri:
        exact: /dashboard.html
    route:
    - destination:
        host: blackjack-frontend
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackjack-users
spec:
  hosts:
  - "<<REPLACE WITH YOUR BOOKINFO APP URL>>"
  gateways:
  - blackjack-gateway
  http:
  - match:
    - uri:
        exact: /blackjack/user
    route:
    - destination:
        host: blackjack-users
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackjack-payment
spec:
  hosts:
  - "<<REPLACE WITH YOUR BOOKINFO APP URL>>"
  gateways:
  - blackjack-gateway
  http:
  - match:
    - uri:
        exact: /blackjack/user/payment
    route:
    - destination:
        host: blackjack-payment
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackjack-ranking
spec:
  hosts:
  - "<<REPLACE WITH YOUR BOOKINFO APP URL>>"
  gateways:
  - blackjack-gateway
  http:
  - match:
    - uri:
        exact: /blackjack/user/ranking
    route:
    - destination:
        host: blackjack-ranking
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackjack-status
spec:
  hosts:
  - "<<REPLACE WITH YOUR BOOKINFO APP URL>>"
  gateways:
  - blackjack-gateway
  http:
  - match:
    - uri:
        exact: /blackjack/status
    route:
    - destination:
        host: blackjack-status
        port:
          number: 8080
