apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: blackjack-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "blackjack-frontend-blackjack.apps.cluster-chcompra-2f88.chcompra-2f88.open.redhat.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackjack
spec:
  hosts:
  - "blackjack-frontend-blackjack.apps.cluster-chcompra-2f88.chcompra-2f88.open.redhat.com"
  gateways:
  - blackjack-gateway
  http:
  - match:
    - uri:
        exact: /blackjack.html
    - uri:
        exact: /dashboard.html
    route:
    - destination:
        host: blackjack-frontend
        port:
          number: 8080
